import { readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/**
 * src/visualizers/*Visualizer.ts（ただし基底の Visualizer.ts は除く）を走査し、
 * それらを default import して registry に登録する src/app/plugins.generated.ts を吐く。
 *
 * これにより新しいプラグインは「src/visualizers/ にファイルを1つ足す → ビルド」だけで
 * 有効になる（手で登録行を書く必要がない）。機構は src/app/ 側にまとめてある。
 */
export function generatePlugins() {
  const dir = 'src/visualizers';
  const files = readdirSync(dir)
    .filter((f) => f.endsWith('Visualizer.ts') && f !== 'Visualizer.ts')
    .sort();

  const imports = files.map((f, i) => `import P${i} from '../visualizers/${f.replace(/\.ts$/, '')}';`);
  const regs = files.map((_, i) => `registry.register(() => new P${i}());`);

  const out = `// AUTO-GENERATED by gen-plugins.mjs — do not edit.
// src/visualizers/*Visualizer.ts を自動で登録する。
import { registry } from './registry';
${imports.join('\n')}

${regs.join('\n')}
`;

  writeFileSync('src/app/plugins.generated.ts', out);
  console.log(`gen-plugins: ${files.length} plugin(s) → src/app/plugins.generated.ts`);
}

// 直接実行されたときだけ生成（build.mjs からは import して呼ぶ）
if (process.argv[1] === fileURLToPath(import.meta.url)) generatePlugins();
